version: '{build}'
image: Ubuntu1804
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  project: HtmlBuilder.sln
