version: '{build}'
image: Visual Studio 2019 Preview
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
