trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2022'

steps:
- checkout: self
  lfs: true
- task: UseDotNet@2
  displayName: install .NET 6 SDK
  inputs:
    packageType: sdk
    version: 6.x
- task: UseDotNet@2
  displayName: install .NET Core 3.1 SDK
  inputs:
    packageType: sdk
    version: 3.1.x
- task: CmdLine@2
  displayName: install BomSweeper.GlobalTool
  inputs:
    script: dotnet tool install -g BomSweeper.GlobalTool
- task: CmdLine@2
  displayName: check BOMs
  inputs:
    script: bomsweeper '**/*.cs' '**/*.csproj' '**/*.sln'
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build HtmlBuilder.Test'
- task: PublishCodeCoverageResults@1
  displayName: publish coverage report
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'HtmlBuilder.Test/coverage.cobertura.xml'
