version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run:
          name: Register Microsoft key and feed
          command: |
            apt-get -y update
            apt-get -y install gnupg
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
            mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
            wget -q https://packages.microsoft.com/config/debian/9/prod.list
            mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
            chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
            chown root:root /etc/apt/sources.list.d/microsoft-prod.list
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get -y install git-lfs
            git lfs install
      - run:
          name: Install SSH client
          command: |
            apt-get -y install ssh-client
      - checkout
      - run:
          name: Check BOM
          command: |
            apt-get -y install dotnet-sdk-3.1
            dotnet tool install -g BomSweeper.GlobalTool
            /root/.dotnet/tools/bomsweeper '**/*.cs' '**/*.csproj' '**/*.sln'
      - run:
          name: Build
          command: |
            dotnet build
      - run:
          name: Test
          command: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            rm -rf MsTestResults
            dotnet test --collect:"XPlat Code Coverage" --results-directory MsTestResults
            /root/.dotnet/tools/reportgenerator -reports:MsTestResults/*/coverage.cobertura.xml -targetdir:Coverlet-html
      - store_artifacts:
          path: /root/project/Coverlet-html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
