version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100
    steps:
      - run:
          name: Register Microsoft key and feed
          command: |
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
            mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
            wget -q https://packages.microsoft.com/config/debian/9/prod.list
            mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
            chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
            chown root:root /etc/apt/sources.list.d/microsoft-prod.list
      - run:
          name: Install .NET Core runtime 2.2
          command: |
            apt-get install apt-transport-https
            apt-get update
            apt-get -y install dotnet-runtime-2.2
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get install git-lfs
      - checkout
      - run: pwd
      - run: dotnet restore
      - run:
          name: Check BOM
          command: |
            dotnet tool install -g BomSweeper.GlobalTool
            /root/.dotnet/tools/bomsweeper '**/*.cs' '**/*.csproj' '**/*.sln'
      - run: dotnet build
      - run:
          name: Test
          command: |
            dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --no-build HtmlBuilder.Test
      - run:
          name: Coverage
          command: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            /root/.dotnet/tools/reportgenerator --reports:HtmlBuilder.Test/coverage.opencover.xml --targetdir:Coverlet-html
      - store_artifacts:
          path: /root/project/Coverlet-html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
